version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - unconvert
    - unparam
    - bodyclose

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam

  exclusions:
    generated: strict

formatters:
  enable:
    - gofmt

  exclusions:
    generated: strict
