run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - misspell
    - unconvert
    - unparam
    - bodyclose

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam

issues:
  exclude-dirs:
    - api/v1alpha1/zz_generated.*
