//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BehaviorConfig) DeepCopyInto(out *BehaviorConfig) {
	*out = *in
	out.InitializationPeriod = in.InitializationPeriod
	out.MetricsWindow = in.MetricsWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BehaviorConfig.
func (in *BehaviorConfig) DeepCopy() *BehaviorConfig {
	if in == nil {
		return nil
	}
	out := new(BehaviorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskAutoscalePolicy) DeepCopyInto(out *DiskAutoscalePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskAutoscalePolicy.
func (in *DiskAutoscalePolicy) DeepCopy() *DiskAutoscalePolicy {
	if in == nil {
		return nil
	}
	out := new(DiskAutoscalePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskAutoscalePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskAutoscalePolicyList) DeepCopyInto(out *DiskAutoscalePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiskAutoscalePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskAutoscalePolicyList.
func (in *DiskAutoscalePolicyList) DeepCopy() *DiskAutoscalePolicyList {
	if in == nil {
		return nil
	}
	out := new(DiskAutoscalePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskAutoscalePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskAutoscalePolicySpec) DeepCopyInto(out *DiskAutoscalePolicySpec) {
	*out = *in
	if in.PVCSelector != nil {
		in, out := &in.PVCSelector, &out.PVCSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	out.ScaleUp = in.ScaleUp
	out.ScaleDown = in.ScaleDown
	out.Constraints = in.Constraints
	out.Behavior = in.Behavior
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskAutoscalePolicySpec.
func (in *DiskAutoscalePolicySpec) DeepCopy() *DiskAutoscalePolicySpec {
	if in == nil {
		return nil
	}
	out := new(DiskAutoscalePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskAutoscalePolicyStatus) DeepCopyInto(out *DiskAutoscalePolicyStatus) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]DiskStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskAutoscalePolicyStatus.
func (in *DiskAutoscalePolicyStatus) DeepCopy() *DiskAutoscalePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DiskAutoscalePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskMetricsSnapshot) DeepCopyInto(out *DiskMetricsSnapshot) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskMetricsSnapshot.
func (in *DiskMetricsSnapshot) DeepCopy() *DiskMetricsSnapshot {
	if in == nil {
		return nil
	}
	out := new(DiskMetricsSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskStatus) DeepCopyInto(out *DiskStatus) {
	*out = *in
	if in.LastScaleUp != nil {
		in, out := &in.LastScaleUp, &out.LastScaleUp
		*out = (*in).DeepCopy()
	}
	if in.LastScaleDown != nil {
		in, out := &in.LastScaleDown, &out.LastScaleDown
		*out = (*in).DeepCopy()
	}
	if in.LastMetrics != nil {
		in, out := &in.LastMetrics, &out.LastMetrics
		*out = new(DiskMetricsSnapshot)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskStatus.
func (in *DiskStatus) DeepCopy() *DiskStatus {
	if in == nil {
		return nil
	}
	out := new(DiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleDirectionConfig) DeepCopyInto(out *ScaleDirectionConfig) {
	*out = *in
	out.Cooldown = in.Cooldown
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleDirectionConfig.
func (in *ScaleDirectionConfig) DeepCopy() *ScaleDirectionConfig {
	if in == nil {
		return nil
	}
	out := new(ScaleDirectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConstraints) DeepCopyInto(out *ScalingConstraints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConstraints.
func (in *ScalingConstraints) DeepCopy() *ScalingConstraints {
	if in == nil {
		return nil
	}
	out := new(ScalingConstraints)
	in.DeepCopyInto(out)
	return out
}
